<a href="https://colab.research.google.com/github/ameyadike/AnomalyDetectionWithARIMA/blob/main/NumpyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy is a linear algebra library for python. It is important library in Data 
Science since almost all libraries in the PyData Ecosystem rely on NumPy as one of their main buildin blocks.
Numpy is also fast as it has the bindings to C libraries.

# NumPy Arrays

In [2]:
import numpy as np

In [4]:
# Casting list as an array
my_list = [1,2,3]
arr = np.array(my_list)
arr

array([1, 2, 3])

In [5]:
# Casting matrices
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# Create array with builtin methods
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Adding step size
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
# Arrays of zeros
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# Arrays of ones
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# Linspace gives evenly spaced points in given range
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
# Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# Random numbers array uniformly distributed over 0 to 1
np.random.rand(5)

array([0.98525437, 0.58692124, 0.73871784, 0.87582031, 0.9242543 ])

In [17]:
np.random.rand(5,5)

array([[0.11263981, 0.78301421, 0.34908824, 0.47220956, 0.42742442],
       [0.11331441, 0.8211549 , 0.08511993, 0.13232765, 0.02055797],
       [0.81348657, 0.49043747, 0.6025276 , 0.72356274, 0.04252302],
       [0.96323374, 0.56971677, 0.52744787, 0.55102379, 0.32899121],
       [0.18561545, 0.82160013, 0.71433956, 0.92247258, 0.64540868]])

In [19]:
# Using standard distribution / Gaussian distribution
np.random.randn(2)

array([-1.53989656, -0.20143588])

In [21]:
np.random.randint(1,100)

7

In [23]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 8, 44, 40, 15, 44, 24, 34, 24, 43, 19])

In [25]:
# Reshapinng 
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
# Index location of max value
ranarr.argmax()

1

In [27]:
# Index location of min value
ranarr.argmin()

0

In [29]:
# Shape of the vector
arr.shape

(25,)

In [30]:
arr.dtype

dtype('int64')

# NumPy Indexing and Selection

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
arr[8]

8

In [34]:
# Indexing starts at 0
arr[1:5]

array([1, 2, 3, 4])

In [35]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [36]:
arr[8:]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
# braodcasting
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [38]:
slice_of_arr = arr[8:11]

In [39]:
slice_of_arr[:] = 99

In [40]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,  99,  99,  99,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [41]:
# if we perform operation on the slice of an array, the original array also changes

In [43]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [44]:
arr_2d[0][0]

5

In [45]:
arr_2d[1][2]

30

In [46]:
arr_2d[2,1]

40

In [47]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [48]:
# Conditional selection
arr = np.arange(1,11)

In [50]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [51]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

# NumPy Operations

In [52]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [54]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [56]:
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [57]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])